export {
  GET_TRENDING_ANIME,
  GET_POPULAR_ANIME,
  GET_TOP_RATED_ANIME,
  GET_UPCOMING_ANIME,
  GET_RECENTLY_COMPLETED_ANIME,
  SEARCH_ANIME,
} from './listQueries';

export { GET_ANIME_DETAILS } from './detailQueries';

export {
  ANIME_BASIC_FIELDS,
  PAGE_INFO_FIELDS,
  ANIME_DETAILED_FIELDS,
} from '../fragments';
